secrets: /config/secrets.yaml
appdaemon:
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 0
  time_zone: Europe/London
  plugins:
    HASS:
      type: hass
http:
  url: http://127.0.0.1:5050
hadashboard:
admin:
api:
