## Message Notifications
- id: house_alarm_message_on
  alias: "Alarm: Turned On"
  trigger:
  - entity_id: alarm_control_panel.primary_alarm_panel
    from: pending
    platform: state
    to: armed_away
  condition: []
  action:
  - service: notify.ios_colin
    data:
      message: Alarm has been turned on
      title: Alarm On
  - service: notify.slack
    data:
      title: Alarm Status On
      message: House alarm has been turned on
      
- id: house_alarm_message_off
  alias: "Alarm: Turned Off"
  trigger:
  - entity_id: alarm_control_panel.primary_alarm_panel
    platform: state
    to: disarmed
  condition: []
  action:
  - service: notify.ios_colin
    data:
      message: The alarm has been turned off
      title: Alarm Off
  - service: notify.slack
    data:
      title: Alarm Status Off
      message: House alarm has been turned off

## Alarm Panel - Start countdown if triggered
- id: house_alarm_trigger_if_armed_away
  alias: "Alarm: Trigger the panel if armed away"
  trigger:
  - entity_id: binary_sensor.front_door
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.landing_motion_sensor
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.living_room_motion_sensor
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.hallway_motion_sensor
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.primary_alarm_panel
    state: armed_away
  action:
  - data:
      entity_id: alarm_control_panel.primary_alarm_panel
    service: alarm_control_panel.alarm_trigger
    
- id: house_alarm_trigger_if_armed_home
  alias: "Alarm: Trigger the alarm if armed home"
  trigger:
  - entity_id: binary_sensor.front_door
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.living_room_motion_sensor
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.hallway_motion_sensor
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.primary_alarm_panel
    state: armed_home
  action:
  - data:
      entity_id: alarm_control_panel.primary_alarm_panel
    service: alarm_control_panel.alarm_trigger    
    
## Alarm Panel - Start Alarm Sequence    
- id: house_alarm_triggered
  alias: "Alarm: Triggered Alert"
  trigger:
  - entity_id: alarm_control_panel.primary_alarm_panel
    platform: state
    to: triggered
  condition: []
  action:
  - service: script.intruder_alert
    data: {}
    
## Alarm Panel - Intruder Disable Sequence
- id: house_alarm_intruder_reset
  alias: "Alarm: Intruder Reset"
  trigger:
  - entity_id: alarm_control_panel.primary_alarm_panel
    platform: state
    from: triggered
    to: disarmed
  condition: []
  action:
  - service: script.intruder_alert_reset
    data: {}