- id: ifttt_alexa_incomming_webhook
  alias: "IFTTT: Incomming Webhook"
  trigger:
  - event_data:
      action: call_service
    event_type: ifttt_webhook_received
    platform: event
  condition: []
  action:
  - service_template: '{{ trigger.event.data.service }}'
    data: {}