- platform: manual_mqtt
  name: "Primary Alarm Panel"
  state_topic: "home/alarm"
  command_topic: "home/alarm/set"
  pending_time: 30
  trigger_time: 1800
  disarm_after_trigger: false
  delay_time: 0
  armed_home:
    pending_time: 30
    delay_time: 0
  armed_away:
    pending_time: 30
    delay_time: 0
