smart_home:
  locale: en-GB
  endpoint: https://api.eu.amazonalexa.com/v3/events
  filter:
    exclude_domains:
      - light
      - automation
      - group
      - sensor
      - media_player
      - switch
      - binary_sensor
      - input_number
      - input_sensor
      - input_boolean
      - scene
      - person
      - zone
      - device_tracker
      - update
      - weather
      - sun
      - camera
      - timer
    include_entities:
      - light.kitchen
      - light.dining_room
      - light.hallway
      - light.study
      - light.craft_room
      - light.bedroom_lamp_colin
      - light.living_room_uplight
      - light.living_room_reading_light
      - light.living_room_lamp
      - light.colin_s_office_lamp
      - light.guest_room
      - light.living_room_wall
      - binary_sensor.front_door_sensor_iaszone
      - binary_sensor.hallway_motion_sensor_iaszone
      - binary_sensor.landing_motion_sensor_iaszone

