##########
# Binary Sensors for the house
##########


### Pingable hosts - Sensors

  # Power Sensor (ICMP)
  - platform: ping
    name: "Power Sensor Check"
    host: !secret power_sensor_host
    count: 2

  # Solar Sensor (ICMP)
  - platform: ping
    name: "Solar Sensor Check"
    host: !secret solar_sensor_host
    count: 2

  # Loft01 Sensor (ICMP)
  - platform: ping
    name: "Loft01 Sensor Check"
    host: !secret loft01_sensor_host
    count: 2

  # Office Sensor (ICMP)
  - platform: ping
    name: "Office Sensor Check"
    host: !secret office_sensor_host
    count: 2

### Pingable hosts - Server

  # Server 1 (ICMP)
  - platform: ping
    name: "Server 1"
    host: !secret server1_host
    count: 2

  # Server 2 (ICMP)
  - platform: ping
    name: "Server 2"
    host: !secret server2_host
    count: 2