  - platform: icloud3
    username: !secret icloud_username
    password: !secret icloud_password
    waze_region: EU
    track_devices:
      - !secret icloud_colins_device
  - platform: tile
    username: !secret tile_username
    password: !secret tile_password