filter:
  include_entities:
    - alarm_control_panel.alarm_panel
    - light.kitchen
    - light.dining_room
    - light.hallway
    - light.study
    - light.craft_room
    - light.guest_room
    - light.landing
    - light.office_lights
    - light.bedroom
    - binary_sensor.front_door_sensor_iaszone
    - binary_sensor.hallway_motion_sensor_iaszone
    - binary_sensor.landing_motion_sensor_iaszone
    - climate.anna_s_study
    - climate.colin_s_office
    - climate.dining_room
    - climate.kitchen_valve
    - climate.living_room_chair
    - climate.living_room_window
    - climate.zone_1_hallway
    - climate.zone_2_bedroom
    - sensor.office_room_temperature
    - sensor.office_room_humidity
    - sensor.office_room_pressure
    - sensor.loft_temperature
    - sensor.kitchen_sensor
    - sensor.kitchen_sensor_2
    - sensor.kitchen_sensor_3
