#######
# Input Booleans
#######

# Enable and disable the light automation around the house
home_automation:
  name: Light Automation
  icon: mdi:lightbulb
      
# Guest mode means that others are in the house, so return some to manual
guest_mode:
  name: Guest Mode
  icon: mdi:account-group

# Lights in the living room need to be separted incase of visitors
living_room_auto:
  name: Living Room Automatic Lights
  icon: mdi:lightbulb
  
# Rubbish Bin Reminders
rubbish_bin_reminder:
  name: Rubbish Bin Reminder
  icon: mdi:trash-can
  
# Rubbish Bin Snooze
rubbish_bin_reminder_snooze:
  name: Rubbish Bin Reminder Snoozed
  icon: mdi:trash-can
  
# Recycling Bin Reminders
recycling_bin_reminder:
  name: Recycling Bin Reminder
  icon: mdi:recycle
  
# Recycling Bin Snooze
recycling_bin_reminder_snooze:
  name: Recycling Bin Reminder Snoozed
  icon: mdi:recycle