- platform: group
  name: Living Room Lights
  entities:
    - light.living_room_light_left
    - light.living_room_light_right

- platform: group
  name: Living Room Lamps
  entities:
    - light.living_room_lamp
    - light.living_room_lamp_2
    - light.uplight
    
- platform: group
  name: Staircase Lights
  entities:
    - light.hallway_light
    - light.landing_light
