- id: weekly_backup
  alias: Weekly Backup of Home Assistant
  trigger:
    platform: time
    at: '3:00:00'
  condition:
    condition: time
    weekday:
    - tue
  action:
    service: hassio.snapshot_full
    data_template:
      name: '{{ now().strftime(''%Y-%m-%d'') }}-Home-Assistant'
      password: !secret backup_password