- id: left_house_check
  alias: 'Left House: Ensure house has been hibernated'
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: person.colin_barker
    from: home
  condition:
  - condition: state
    entity_id: binary_sensor.no_one_home
    state: 'on'
  action:
  - delay: 00:05:00
  - condition: state
    entity_id: binary_sensor.no_one_home
    state: 'on'
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  - service: notify.ios_colin
    data:
      title: Detected leaving the house
      message: Do you want to hibernate the house?
      data:
        push:
          category: "hibernate_house"
          
- id: return_home_check
  alias: Colin's Home
  trigger:
  - entity_id: person.colin_barker
    platform: state
    to: home
  condition: []
  action:
  - data:
      event: PushMessage
      value1: Welcome Home Colin!
      value2: You have been detected at home!
    service: ifttt.trigger
  - service: notify.ios_colin
    data:
      title: Welcome Home Colin!
      message: Do you wish to unlock the house?
      data:
        push:
          category: "return_home"
          
- id: ios_hibernate_house
  alias: 'IOS Action: Hibernate House'
  initial_state: 'on'
  trigger:
  - platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: HIBERNATE_HOUSE
  action:
  - service: script.hibernate_house
    data: {}
  
- id: ios_arm_alarm
  alias: 'IOS Action: Arm Alarm'
  initial_state: 'on'
  trigger:
  - platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: ALARM_ON
  action:
    - service: script.arm_alarm
      data: {}
      
- id: ios_return_home
  alias: 'IOS Action: Return Home'
  initial_state: 'on'
  trigger:
  -  platform: event
     event_type: ios.notification_action_fired
     event_data:
       actionName: RETURN_HOME
  action:
    - service: script.return_home
      data: {}
      
- id: ios_heating_on_auto
  alias: 'IOS Action: Heating On Automatic'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: HEATING_ON_AUTO
  action:
    - service: script.heating_on_auto
      data: {}
  
- id: ios_heating_off
  alias: 'IOS Action: Heating On'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: HEATING_OFF
  action:
    - service: script.heating_off
      data: {}

- id: '1556409085689'
  alias: Weekly Backup of Home Assistant
  trigger:
    platform: time
    at: '3:00:00'
  condition:
    condition: time
    weekday:
    - tue
  action:
    service: hassio.snapshot_full
    data_template:
      name: '{{ now().strftime(''%Y-%m-%d'') }}-Home-Assistant'
      password: !secret backup_password

- id: '1557067959518'
  alias: Colin's Away
  trigger:
  - entity_id: person.colin_barker
    from: home
    platform: state
    to: not_home
  condition: []
  action:
  - data:
      event: PushMessage
      value1: Have fun Colin!
      value2: You have been detected leaving the house
    service: ifttt.trigger
- id: '1557744413114'
  alias: MQTT Weather Push
  trigger:
  - minutes: '/5'
    platform: time_pattern
  condition: []
  action:
  - data:
      #payload_template: '{''weather'':{{states.weather.dark_sky.attributes}}}'
      payload_template: '{''weather'': { ''temperature'': {{ states.sensor.front_house_sensor_temperature.state }}, ''humidity'': {{ states.weather.met_office_billingshurst.attributes["humidity"] }}, ''ozone'': {{ states.weather.dark_sky.attributes["ozone"] }}, ''pressure'': {{ states.weather.dark_sky.attributes["pressure"] }}, ''wind_bearing'': {{ states.weather.dark_sky.attributes["wind_bearing"] }}, ''wind_speed'': {{ states.weather.met_office_billingshurst.attributes["wind_speed"] }}, ''visibility'': {{ states.weather.dark_sky.attributes["visibility"] }}, ''forecast'': {{ states.weather.dark_sky.attributes["forecast"] }} } }'
      retain: true
      topic: alarmpanel/command
    service: mqtt.publish
- id: '1557746486813'
  alias: MQTT Sun Push
  trigger:
  - minutes: '/15'
    platform: time_pattern
  condition: []
  action:
  - data:
      payload_template: '{''sun'':''{{states(''sun.sun'')}}''}'
      retain: true
      topic: alarmpanel/command
    service: mqtt.publish
- id: '1577750597410'
  alias: Reading Light Toggle
  description: Switch the reading light on/off
  trigger:
  - event_data:
      event: 1002
      id: reading_light_switch
    event_type: deconz_event
    platform: event
  condition: []
  action:
  - device_id: 9a531e5ddb6d4a34ad12fa4a67ca1742
    domain: light
    entity_id: light.reading_light_2
    type: toggle
- id: '1577750706281'
  alias: Turn off Reading Lights
  description: ''
  trigger:
  - device_id: 8177e7839fb141a9ac5df2bdeb0f6e37
    domain: deconz
    platform: device
    subtype: turn_on
    type: remote_button_long_press
  condition: []
  action:
  - device_id: b2842355023b4d2d8a50fd1d60c48a77
    domain: light
    entity_id: light.uplight
    type: turn_off
  - device_id: 9a531e5ddb6d4a34ad12fa4a67ca1742
    domain: light
    entity_id: light.reading_light_2
    type: turn_off
- id: 124fe1b0df914fab121b82a92f2ff4a2
  alias: 'Reading Light: Light up'
  description: ''
  trigger:
  - event_data:
      event: 2002
      id: reading_light_switch
    event_type: deconz_event
    platform: event
  condition: []
  action:
  - alias: ''
    data_template:
      brightness: '{% set bri = state_attr(''light.reading_light_2'', ''brightness'')
        | int %}  {{ [bri+30, 249] | min }}

        '
      entity_id: light.reading_light_2
    service: light.turn_on
- id: '1577751463616'
  alias: 'Reading Light: Dim Light'
  description: ''
  trigger:
  - event_data:
      event: 3002
      id: reading_light_switch
    event_type: deconz_event
    platform: event
  condition: []
  action:
  - data_template:
      brightness: '{% set bri = state_attr(''light.reading_light_2'', ''brightness'')
        | int %} {{ [bri-30, 0] | max }}

        '
      entity_id: light.reading_light_2
    service: light.turn_on
- id: '1577751155836'
  alias: 'Stand Light: Light up'
  description: ''
  trigger:
  - event_data:
      event: 5002
      id: reading_light_switch
    event_type: deconz_event
    platform: event
  condition: []
  action:
  - alias: ''
    data_template:
      brightness: '{% set bri = state_attr(''light.uplight'', ''brightness'') | int
        %}  {{ [bri+30, 249] | min }}

        '
      entity_id: light.uplight
    service: light.turn_on
- id: 124fe1b0df514fab888b82a92f2ff4a2
  alias: 'Stand Light: Dim Light'
  description: ''
  trigger:
  - event_data:
      event: 4002
      id: reading_light_switch
    event_type: deconz_event
    platform: event
  condition: []
  action:
  - data_template:
      brightness: '{% set bri = state_attr(''light.uplight'', ''brightness'') | int
        %} {{ [bri-30, 0] | max }}

        '
      entity_id: light.uplight
    service: light.turn_on
