
# Loads default set of integrations. Do not remove.
homeassistant: !include includes/homeassistant.yaml
default_config:
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
    
# HTTP Configurations
http: !include includes/http.yaml
api:

# Database Configuration
recorder: !include includes/recorder.yaml
influxdb: !include includes/influxdb.yaml

# Manual Addons
alexa: !include includes/alexa.yaml
device_tracker: !include includes/device_tracker.yaml
mqtt: !include includes/mqtt.yaml
sensor: !include includes/sensor.yaml
binary_sensor: !include includes/binary_sensor.yaml
alarm_control_panel: !include includes/alarm_control_panel.yaml
homekit: !include includes/homekit.yaml
waste_collection_schedule: !include includes/waste_collection_schedule.yaml

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
